// <auto-generated />
using FakeStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FakeStore.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20210711180824_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FakeStore.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("inventoryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("inventoryNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("inventoryPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("inventoryQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryID");

                    b.ToTable("Inventory1");
                });

            modelBuilder.Entity("FakeStore.Orders", b =>
                {
                    b.Property<int>("OrdersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("allTotal")
                        .HasColumnType("REAL");

                    b.Property<string>("productName")
                        .HasColumnType("TEXT");

                    b.Property<double>("productPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("productQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("subTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("taxes")
                        .HasColumnType("REAL");

                    b.Property<double>("total")
                        .HasColumnType("REAL");

                    b.HasKey("OrdersId");

                    b.HasIndex("InventoryID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("FakeStore.Orders", b =>
                {
                    b.HasOne("FakeStore.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
